In [ ]:
import numpy as np
import rasterio
from sklearn.metrics import confusion_matrix, cohen_kappa_score, accuracy_score

# 读取两幅TIFF文件
def read_tif(file_path):
    with rasterio.open(file_path) as src:
        data = src.read(1)  # 读取第一波段
        return data.flatten()  # 展平为一维数组

# 假设文件路径
true_tif = 'E:/学习资料/竞赛/第三届全国大学生乡村国土空间价值提升规划设计大赛（昆明赛区）/实验数据/FLUS/data/2017output/2022.tif'
pred_tif = 'E:/学习资料/竞赛/第三届全国大学生乡村国土空间价值提升规划设计大赛（昆明赛区）/实验数据/FLUS/save/output/2023_nature.tif'

# 读取数据并过滤无效值（如nodata）
y_true = read_tif(true_tif)
y_pred = read_tif(pred_tif)

# 确保两幅图像尺寸一致
assert len(y_true) == len(y_pred), "两幅图像尺寸不一致！"

# 计算混淆矩阵和Kappa系数
conf_matrix = confusion_matrix(y_true, y_pred)
kappa = cohen_kappa_score(y_true, y_pred)
accuracy = accuracy_score(y_true, y_pred)

# 输出结果
print("混淆矩阵（行：真实类别，列：预测类别）：\n", conf_matrix)
print("Kappa系数：", kappa)
print("总体精度：", accuracy)

[65535 65535 65535 ... 65535 65535 65535]
[0 0 0 ... 0 0 0]
混淆矩阵（行：真实类别，列：预测类别）：
 [[    0     0     0     0     0     0     0     0     0]
 [    0   131    29     4     0    45     0    19     0]
 [    0    66 76311    16   241   671     4  2205     0]
 [    0     0     0     7     0     0     0     7     0]
 [    0     0    30     0   169    47     0    90     0]
 [    0     5   987    13  2060 17565   224   382     0]
 [    0     0     0     0     0     3    72     0     0]
 [    0    54  1485   151   976  1090    10  9410     0]
 [83949     0     0     0     0     0     0     0     0]]
Kappa系数： 0.42178843342505656
总体精度： 0.5221681576402321
